### PR TITLE
[EPG-36553] Expand SOAP Client for Java

### PR DESCRIPTION
**Pull request by dpauli**
- expand product with energy label
- expand product with datasheets in english / german
- update product with energy label and datasheet

### CODE REVIEW

**Comment by otrosien** [comment]
ok to test
add to whitelist

**Comment by kayabendroth-epages** [comment]
retest this please

**Comment by otrosien** [comment]
retest this please

**Comment by otrosien** [comment]
retest this please

**Comment by otrosien** [comment]
retest this please

**Comment by otrosien** [comment]
retest this please

**Comment by otrosien** [comment]
retest this please

**Comment by otrosien** [comment]
retest this please

**Pull request merged**
